#!/usr/bin/env python3
"""gen_tree.py — Train a DecisionTreeClassifier on Rinha reference vectors
and emit Go source code for src/tree_model_gen.go.

Usage:
    python3 scripts/gen_tree.py <references.json[.gz]> <output.go>

The reference JSON has items:
    {"vector": [f0..f13], "label": "legit"|"fraud"}

Feature indices match Go's handleFraudScore() normalization (pre-weight):
    0  amount / max_amount
    1  installments / max_installments
    2  (amount / avg_amount) / amount_vs_avg_ratio
    3  hour / 23
    4  weekday / 6
    5  minutes_since_last / max_minutes  (-1 if no last tx)
    6  km_from_current / max_km          (-1 if no last tx)
    7  km_from_home / max_km
    8  tx_count_24h / max_tx_count_24h
    9  is_online (0 or 1)
    10 card_present (0 or 1)
    11 unknown_merchant (0=known, 1=unknown)
    12 mcc_risk
    13 merchant_avg / max_merchant_avg
"""
from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path


def load_references(path: str):
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as fh:
        data = json.load(fh)
    X = [entry["vector"] for entry in data]
    y = [1 if entry["label"] == "fraud" else 0 for entry in data]
    return X, y


def emit_go(clf, n_train: int, out_path: str) -> None:
    tree = clf.tree_
    n_nodes = tree.node_count

    # int16 is safe when total nodes < 32768.
    idx_type = "int16" if n_nodes < 32768 else "int32"

    lines: list[str] = []
    lines += [
        "// Code generated by scripts/gen_tree.py; DO NOT EDIT.",
        "package main",
        "",
        "// treeNode is one node in the compiled decision tree.",
        "// feature == treeLeafFeature (-1) means leaf; fraud gives the leaf prediction.",
        "type treeNode struct {",
        "\tthreshold float32",
        f"\tleft      {idx_type}   // child index when feature <= threshold",
        f"\tright     {idx_type}   // child index when feature > threshold",
        "\tfeature   int8    // treeLeafFeature (-1) for leaf nodes",
        "\tfraud     bool",
        "\tpurity    float32 // fraction of training samples matching the leaf prediction",
        "}",
        "",
        "const treeLeafFeature int8 = -1",
        "",
        "// treeConfidenceThreshold: leaf purity must be >= this to skip the HIVF index.",
        "// 0.80 means 80% of training samples in this leaf agree on the prediction.",
        "const treeConfidenceThreshold float32 = 0.80",
        "",
        f"// treeNodes holds the compiled decision tree ({n_nodes} nodes, {n_train} training samples).",
        "var treeNodes = []treeNode{",
    ]

    LEAF_FEAT = -2  # sklearn TREE_UNDEFINED

    for i in range(n_nodes):
        feat = int(tree.feature[i])
        thresh = float(tree.threshold[i])
        left = int(tree.children_left[i])
        right = int(tree.children_right[i])

        if feat == LEAF_FEAT:
            vals = tree.value[i][0]          # shape: [n_classes]
            total = vals[0] + vals[1]
            is_fraud = vals[1] > vals[0]
            dominant = vals[1] if is_fraud else vals[0]
            purity = float(dominant / total) if total > 0 else 1.0
            lines.append(
                f"\t{{feature: treeLeafFeature, left: 0, right: 0, threshold: 0,"
                f" fraud: {'true' if is_fraud else 'false'}, purity: {purity:.7f}}},"
            )
        else:
            lines.append(
                f"\t{{feature: {feat}, left: {left}, right: {right},"
                f" threshold: {thresh:.8f}, fraud: false, purity: 0}},"
            )

    lines += [
        "}",
        "",
        "// treePredict traverses the compiled decision tree.",
        "// Returns (isFraud bool, confident bool).",
        "// confident=false means the HIVF index should be consulted instead.",
        "func treePredict(f *[dims]float32) (fraud bool, confident bool) {",
        "\ti := 0",
        "\tfor {",
        "\t\tn := treeNodes[i]",
        "\t\tif n.feature == treeLeafFeature {",
        "\t\t\treturn n.fraud, n.purity >= treeConfidenceThreshold",
        "\t\t}",
        "\t\tif f[n.feature] <= n.threshold {",
        "\t\t\ti = int(n.left)",
        "\t\t} else {",
        "\t\t\ti = int(n.right)",
        "\t\t}",
        "\t}",
        "}",
        "",
    ]

    Path(out_path).write_text("\n".join(lines))
    print(f"[gen_tree] written {out_path} ({n_nodes} nodes, {idx_type} indices)", flush=True)


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: gen_tree.py <references.json[.gz]> <output.go>", file=sys.stderr)
        sys.exit(1)

    ref_path, out_path = sys.argv[1], sys.argv[2]

    print(f"[gen_tree] loading {ref_path} ...", flush=True)
    X, y = load_references(ref_path)
    n = len(X)
    fraud_n = sum(y)
    print(f"[gen_tree] loaded {n} references ({fraud_n} fraud, {n - fraud_n} legit)", flush=True)

    from sklearn.tree import DecisionTreeClassifier

    clf = DecisionTreeClassifier(
        max_depth=15,
        min_samples_leaf=20,
        min_impurity_decrease=0,
        random_state=42,
        class_weight="balanced",
    )
    print(
        "[gen_tree] training DecisionTreeClassifier(max_depth=15, min_samples_leaf=20) ...",
        flush=True,
    )
    clf.fit(X, y)

    tree = clf.tree_
    n_nodes = tree.node_count
    preds = clf.predict(X)
    acc = sum(p == t for p, t in zip(preds, y)) / n
    tp = sum(p == 1 and t == 1 for p, t in zip(preds, y))
    fp = sum(p == 1 and t == 0 for p, t in zip(preds, y))
    fn = sum(p == 0 and t == 1 for p, t in zip(preds, y))
    print(
        f"[gen_tree] tree: {n_nodes} nodes, depth={tree.max_depth},"
        f" acc={acc:.4f}, TP={tp}, FP={fp}, FN={fn}",
        flush=True,
    )

    emit_go(clf, n, out_path)


if __name__ == "__main__":
    main()
