// Code generated by scripts/gen_tree.py; DO NOT EDIT.
// Placeholder — replaced during Docker build with a trained DecisionTreeClassifier.
// This single leaf has purity=0 so treePredict always returns confident=false,
// meaning every request falls through to the HIVF index until a real tree is
// compiled in by the Docker tree_trainer stage.
package main

// treeNode is one node in the compiled decision tree.
// feature == treeLeafFeature (-1) means leaf; fraud gives the leaf prediction.
type treeNode struct {
	threshold float32
	left      int16   // child index when feature <= threshold
	right     int16   // child index when feature > threshold
	feature   int8    // treeLeafFeature (-1) for leaf nodes
	fraud     bool
	purity    float32 // fraction of training samples matching the leaf prediction
}

const treeLeafFeature int8 = -1

// treeConfidenceThreshold: leaf purity must be >= this to skip the HIVF index.
// Tune lower to trust the tree more; higher to rely more on HIVF for edge cases.
const treeConfidenceThreshold float32 = 0.88

// treeNodes holds the compiled decision tree (1 node, placeholder).
var treeNodes = []treeNode{
	{feature: treeLeafFeature, left: 0, right: 0, threshold: 0, fraud: false, purity: 0},
}

// treePredict traverses the compiled decision tree.
// Returns (isFraud bool, confident bool).
// confident=false means the HIVF index should be consulted instead.
func treePredict(f *[dims]float32) (fraud bool, confident bool) {
	i := 0
	for {
		n := treeNodes[i]
		if n.feature == treeLeafFeature {
			return n.fraud, n.purity >= treeConfidenceThreshold
		}
		if f[n.feature] <= n.threshold {
			i = int(n.left)
		} else {
			i = int(n.right)
		}
	}
}
